python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 5 --M 5 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 10 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 5 --M 5 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 10 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.8 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.8 --m 10 --M 1 --views 1 --device 1

python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 5 --M 5 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 10 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 5 --M 5 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 10 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.8 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.8 --m 10 --M 1 --views 1 --device 1

python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 5 --M 5 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 10 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 10 --M 1 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 5 --M 5 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 10 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.8 --m 1 --M 10 --views 1 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.8 --m 10 --M 1 --views 1 --device 1


python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 5 --M 5 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.2 --m 10 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 5 --M 5 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.5 --m 10 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.8 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 1 --samples 0.8 --m 10 --M 1 --views 2 --device 1

python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 5 --M 5 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.2 --m 10 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 5 --M 5 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.5 --m 10 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.8 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 2 --samples 0.8 --m 10 --M 1 --views 2 --device 1

python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 5 --M 5 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.2 --m 10 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 10 --M 1 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 5 --M 5 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.5 --m 10 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.8 --m 1 --M 10 --views 2 --device 1
python GLASSTest.py --use_nodeid --use_seed --repeat 5 --dataset hpo_metab --num_powers 3 --samples 0.8 --m 10 --M 1 --views 2 --device 1
